### ISSUE TITLE
unable to generate when ref name contains illegal characters

### ISSUE THREAD

**Issue by joepjoosten** [fortanix/openapi-to-effect#1]
I'm parsing the spec for opensearch (https://github.com/opensearch-project/opensearch-api-specification/releases/download/main-latest/opensearch-openapi.yaml) which contains schemas with names like: "cat._common:CatPitSegmentsRecord" or "_common:AcknowledgedResponseBase", which will result in incorrect typescript code because the schemaId generated is invalid.

```
export const _common:AcknowledgedResponseBase = S.Struct({

  /** For a successful response, this value is always true. On failure, an exception is returned instead. */
  acknowledged: S.Boolean,
}); 
export type _common:AcknowledgedResponseBase = S.Schema.Type<typeof _common:AcknowledgedResponseBase>;
export const _common:AcknowledgedResponseBaseEncoded = S.encodedSchema(_common:AcknowledgedResponseBase);
export type _common:AcknowledgedResponseBaseEncoded = S.Schema.Encoded<typeof _common:AcknowledgedResponseBase>;
```

**Comment by mkrause** [comment]
You're right, the generator was assuming that schemas have names that are valid JS identifiers. I pushed a fix that:

1. Encodes names as valid JS identifiers
2. Adds proper parsing for JSON pointers so that names with special characters (`/` and `~`) don't cause parse errors.

Published as v0.7.0

**Comment by joepjoosten** [comment]
I will check

**Comment by joepjoosten** [comment]
JS identifiers are ok now, but found a new issue #2
