### ISSUE TITLE
Support OpenAPI v3.1 `type` array syntax

### ISSUE THREAD

**Issue by midhun-pk** [fortanix/openapi-to-effect#4]

**Comment by mkrause** [comment]
Quick summary of the issue:

We support OpenAPI v3.1 now, where the schema syntax is now just fully in line with the latest JSON Schema specification. As part of this, the `type` field can now be an array, where the semantics is that the resulting schema validates if it is a valid schema for _any_ of the types in array. See the relevant part of [the spec here](https://json-schema.org/draft/2020-12/json-schema-validation#section-6.1.1):

> If the value of "type" is a string, then an instance validates successfully if its type matches the type represented by the value of the string. If the value of "type" is an array, then an instance validates successfully if its type matches any of the types indicated by the strings in the array.

One consequence of this is that for "nullable" types, we no longer use a `nullable` or `x-nullable` boolean field, instead this is represented as `"type": ["null", <type>]`.

This generator does not support `"type"` as an array yet, we should add it. The desired output is similar to what would happen if we used `anyOf` on the schema with `type` replaced with one of its constituent elements.
